default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: sweets_ball_development

test:
  <<: *default
  database: sweets_ball_test

production:
  <<: *default
  database: sweets_ball_production
  username: sweets_ball
  password: <%= ENV['sweets_ball_DATABASE_PASSWORD'] %>