default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: sweet_trader_development

test:
  <<: *default
  database: sweet_trader_test

production:
  <<: *default
  database: sweet_trader_production
  username: sweet_trader
  password: <%= ENV['sweet_trader_DATABASE_PASSWORD'] %>